openapi: 3.0.3
info:
  title: 晴朗网络 - 接口文档
  description: 该服务的各种辅助功能
  contact:
    name: 中国电信·研究院
    url: http://www.qinglang.cn/
    email: qinglang@qianglang.cn
  version: v1.0
servers:
  - url: http://localhost:8003
    description: Inferred Url
tags:
  - name: PCF签约解约
    extensions:
      x-order: '2147483647'
  - name: SubscribeWhiteController
    extensions:
      x-order: '2147483647'
  - name: apply-rgcode-controller
    extensions:
      x-order: '2147483647'
  - name: atg-log-controller
    extensions:
      x-order: '2147483647'
  - name: call-back-contorller-first
    extensions:
      x-order: '2147483647'
  - name: call-back-controller-adduserprofile
    extensions:
      x-order: '2147483647'
  - name: call-back-controller-common
    extensions:
      x-order: '2147483647'
  - name: call-back-controller-delete
    extensions:
      x-order: '2147483647'
  - name: call-back-controller-last
    extensions:
      x-order: '2147483647'
  - name: call-back-controller-second
    extensions:
      x-order: '2147483647'
  - name: user-status-controller
    extensions:
      x-order: '2147483647'
  - name: 黑名单规则
    extensions:
      x-order: '2147483647'
paths:
  /ctri/atomdir/applyrgCode:
    post:
      tags:
        - apply-rgcode-controller
      summary: 申请业务编码
      operationId: BlackRulePostUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplyrgCode'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«RespDto»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/RespDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/serviceAgent/rest/userSafeMg/selectAtgLog:
    post:
      tags:
        - atg-log-controller
      summary: selectAtgLog
      operationId: selectAtgLogUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AtgLogDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«ResponseEntity«List«AtgLog»»»'}
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AtgLog'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/atomdir/blackRule:
    post:
      tags:
        - 黑名单规则
      summary: 黑名单规则配置
      operationId: BlackRulePostUsingPOST_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlackRule'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«RespDto»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/RespDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/atomdir/blackRuleRemove:
    post:
      tags:
        - 黑名单规则
      summary: 黑名单规则删除
      operationId: BlackRuleRemoveUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BlackRuleRemove'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«RespDto»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/RespDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/l347First:
    post:
      tags:
        - call-back-contorller-first
      summary: 初步配置规则回调
      operationId: testUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/addUserProfile:
    post:
      tags:
        - call-back-controller-adduserprofile
      summary: adduserprofile的回调
      operationId: testUsingPOST_1
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/Common:
    post:
      tags:
        - call-back-controller-common
      summary: 通用回调
      description: 业务编码申请回调、pcf签约回调、pcf解约回调
      operationId: testUsingPOST_2
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/l347Delete:
    post:
      tags:
        - call-back-controller-delete
      summary: 黑名单规则删除回调
      operationId: testUsingPOST_3
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/l347Last:
    post:
      tags:
        - call-back-controller-last
      summary: 黑名单规则配置最后一步回调
      operationId: testUsingPOST_4
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/callBack/l347Second:
    post:
      tags:
        - call-back-controller-second
      summary: 黑名单规则配置第二步
      operationId: testUsingPOST_5
      requestBody:
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/R'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/atomdir/subscribeblack:
    post:
      tags:
        - PCF签约解约
      summary: PCF签约
      operationId: SubscribePostUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscribeblack'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«CompletableFuture«RespDto»»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/CompletableFuture«RespDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/atomdir/unsubscribeblack:
    post:
      tags:
        - PCF签约解约
      summary: PCF解约
      operationId: unSubscribePostUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/unSubscribeblack'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«RespDto»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/RespDto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/atomdir/subscribewhite:
    post:
      tags:
        - SubscribeWhiteController
      summary: SubscribePost
      operationId: SubscribePostUsingPOST_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscribewhite'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«CompletableFuture«RespDto»»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/CompletableFuture«RespDto»'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
  /ctri/serviceAgent/rest/ctsi-5gc-interface-common/safeMg/getNumberState:
    post:
      tags:
        - user-status-controller
      summary: getNumberState
      operationId: getNumberStateUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserStatusDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: >-
                  Error-ModelName{namespace='com.chinatelecom.qinglang.domin',
                  name='R«ResponseEntity«RespUserStatus»»'}
            '*/*':
              schema:
                $ref: '#/components/schemas/RespUserStatus'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      extensions:
        x-order: '2147483647'
components:
  schemas:
    ApplyrgCode:
      title: ApplyrgCode
      type: object
      properties:
        clientname:
          type: string
    AtgLog:
      title: AtgLog
      type: object
      properties:
        executeTime:
          type: string
        failResult:
          type: string
        id:
          type: integer
          format: int64
        imsi:
          type: string
        operator:
          type: string
        operatorCmd:
          type: string
        operatorResult:
          type: string
        operatorTime:
          type: string
          format: date-time
        serial:
          type: string
        vendor:
          type: string
    AtgLogDTO:
      title: AtgLogDTO
      type: object
      properties:
        atgBeginTime:
          type: string
          format: date-time
        atgEndTime:
          type: string
          format: date-time
        isdn:
          type: string
    BlackRule:
      title: BlackRule
      type: object
      properties:
        ipList:
          type: array
          items:
            $ref: '#/components/schemas/L34FilterInfo'
        rgCode:
          type: string
        urlList:
          type: array
          items:
            $ref: '#/components/schemas/L7urlInfo'
    BlackRuleRemove:
      title: BlackRuleRemove
      type: object
      properties:
        ipList:
          type: array
          items:
            $ref: '#/components/schemas/L34FilterInfoRemove'
        rgCode:
          type: string
        urlList:
          type: array
          items:
            $ref: '#/components/schemas/L7urlInfoRemove'
    CompletableFuture«RespDto»:
      title: CompletableFuture«RespDto»
      type: object
      properties:
        cancelled:
          type: boolean
        completedExceptionally:
          type: boolean
        done:
          type: boolean
        numberOfDependents:
          type: integer
          format: int32
    L34FilterInfo:
      title: L34FilterInfo
      type: object
      properties:
        ipTypeId:
          type: string
        l34flowNbr:
          type: integer
          format: int32
        msEndPort:
          type: integer
          format: int32
        msIp:
          type: string
        msIpMask:
          type: string
        msIpMaskLen:
          type: integer
          format: int32
        msIpMaskTypeId:
          type: string
        msStartPort:
          type: integer
          format: int32
        svrEndPort:
          type: integer
          format: int32
        svrIp:
          type: string
        svrIpMask:
          type: string
        svrIpMaskLen:
          type: integer
          format: int32
        svrIpMaskTypeId:
          type: string
        svrStartPort:
          type: integer
          format: int32
    L34FilterInfoRemove:
      title: L34FilterInfoRemove
      type: object
      properties:
        ipTypeId:
          type: string
        l34flowNbr:
          type: integer
          format: int32
    L7urlInfo:
      title: L7urlInfo
      type: object
      properties:
        l7flowNbr:
          type: integer
          format: int32
        url:
          type: string
    L7urlInfoRemove:
      title: L7urlInfoRemove
      type: object
      properties:
        l7flowNbr:
          type: integer
          format: int32
        url:
          type: integer
          format: int32
    ProdOfferInfo:
      title: ProdOfferInfo
      type: object
      properties:
        effDate:
          type: string
        expDate:
          type: string
        offerNbr:
          type: string
        prodOfferInstId:
          type: string
    R:
      title: R
      type: object
      properties:
        code:
          type: integer
          description: 业务状态码，200-成功，其它-失败
          format: int32
        data:
          type: object
          description: 响应数据
        msg:
          type: string
          description: 响应消息
          example: OK
        requestId:
          type: string
          description: 请求id
          example: 1af123c11412e
      description: 通用响应结果
    RespDto:
      title: RespDto
      type: object
      properties:
        resultCode:
          type: integer
          format: int32
        resultMsg:
          type: string
    RespUserStatus:
      title: RespUserStatus
      type: object
      properties:
        done:
          type: string
        mobileNum:
          type: string
        msg:
          type: string
        result:
          type: string
    Subscribeblack:
      title: Subscribeblack
      type: object
      properties:
        isdnList:
          type: array
          items:
            type: string
        rgCode:
          type: string
    Subscribewhite:
      title: Subscribewhite
      type: object
      properties:
        isdn:
          type: string
        prodOfferInfo:
          type: array
          items:
            $ref: '#/components/schemas/ProdOfferInfo'
    UserStatusDto:
      title: UserStatusDto
      type: object
      properties:
        isdn:
          type: string
    unSubscribeblack:
      title: unSubscribeblack
      type: object
      properties:
        isdnList:
          type: array
          items:
            type: string
        rgCode:
          type: string
